"use client";

export type Row=Record<string,any>;
export type GeoFeature={properties:Record<string,any>;geometry:{type:string;coordinates:any}};
export type GeoJSON={type:string;features:GeoFeature[]};
export const norm=(x:any)=>String(x??"").toLowerCase().replace(/district|division|city|province|tehsil/g,"").replace(/[^a-z0-9]/g,"");
export const num=(x:any)=>{const v=Number(String(x??"").replace(/,/g,""));return Number.isFinite(v)?v:null};
export const txt=(x:any)=>String(x??"").trim();
export function flatten(c:any,o:number[][]=[]):number[][]{if(!Array.isArray(c))return o;if(typeof c[0]==="number"&&typeof c[1]==="number")o.push(c);else c.forEach((x:any)=>flatten(x,o));return o}
export function svgPath(f:GeoFeature,b:any,w=780,h=670){const a=f.geometry.type==="Polygon"?f.geometry.coordinates:f.geometry.coordinates.flat();const sx=(x:number)=>20+(x-b.minX)/(b.maxX-b.minX||1)*(w-40),sy=(y:number)=>20+(b.maxY-y)/(b.maxY-b.minY||1)*(h-40);return a.map((r:any)=>r.map((p:number[],i:number)=>`${i?"L":"M"}${sx(p[0]).toFixed(1)},${sy(p[1]).toFixed(1)}`).join(" ")+" Z").join(" ")}
export function shade(v:number|null,min:number,max:number,on:boolean){if(v===null)return on?"rgba(0,77,115,.30)":"rgba(0,77,115,.05)";const t=max===min?.6:Math.max(0,Math.min(1,(v-min)/(max-min)));const alpha=on?.98:.16+t*.78;return `rgba(0,77,115,${alpha})`}

export function MapView({geo,bounds,index,boundary,metric,numeric,min,max,hover,setHover,selected,toggle}:{geo:GeoJSON|null;bounds:any;index:Map<string,Row>;boundary:string;metric:string;numeric:string[];min:number;max:number;hover:any;setHover:(x:any)=>void;selected:string[];toggle:(x:string)=>void}){return <>{geo&&bounds?<svg viewBox="0 0 780 670" className="mapviz" onMouseLeave={()=>setHover(null)}>{geo.features.map((f,i)=>{const name=txt(f.properties[boundary])||`Feature ${i+1}`,k=norm(name),r=index.get(k)||null,v=r?num(r[metric]):null,on=selected.includes(k);return <path key={i} d={svgPath(f,bounds)} fill={shade(v,min,max,on)} stroke={on?"#111":"#626a6c"} strokeWidth={on?1.7:.55} onClick={()=>r&&toggle(k)} onMouseMove={e=>{const q=(e.currentTarget.ownerSVGElement as SVGSVGElement).getBoundingClientRect();setHover({name,row:r,x:e.clientX-q.left,y:e.clientY-q.top})}}/>})}</svg>:<div className="empty">Loading geography…</div>}{hover&&<div className="tooltip" style={{left:Math.min(hover.x+14,590),top:Math.max(hover.y-15,10)}}><b>{hover.name}</b>{hover.row?numeric.map(c=><span key={c}>{c}<strong>{hover.row[c]}</strong></span>):<small>No matched row</small>}<small>Click to cross-filter this geography.</small></div>}<div className="legend"><b>{metric||"Metric"}</b><i/><span>{min.toLocaleString()}</span><span>{max.toLocaleString()}</span></div></>}

export function Bars({rows,metric,label}:{rows:Row[];metric:string;label:string}){const m=Math.max(...rows.map(r=>num(r[metric])||0),1);return <div className="barsviz">{rows.map((r,i)=>{const v=num(r[metric])||0;return <div key={i}><span>{txt(r[label])||`Row ${i+1}`}</span><i><em style={{width:`${Math.max(2,v/m*100)}%`}}/></i><b>{v.toLocaleString()}</b></div>})}</div>}

export function Scatter({rows,x,y,label}:{rows:Row[];x:string;y:string;label:string}){if(!x||!y)return <div className="empty">Choose two numeric metrics.</div>;const p=rows.map(r=>({x:num(r[x]),y:num(r[y]),l:txt(r[label])})).filter(q=>q.x!==null&&q.y!==null) as {x:number;y:number;l:string}[];if(!p.length)return <div className="empty">No comparable numeric pairs.</div>;const a=Math.min(...p.map(q=>q.x)),b=Math.max(...p.map(q=>q.x)),c=Math.min(...p.map(q=>q.y)),d=Math.max(...p.map(q=>q.y)),sx=(v:number)=>55+(v-a)/(b-a||1)*650,sy=(v:number)=>560-(v-c)/(d-c||1)*490;return <svg viewBox="0 0 760 620" className="scatterviz"><line x1="55" y1="560" x2="710" y2="560"/><line x1="55" y1="70" x2="55" y2="560"/>{p.map((q,i)=><circle key={i} cx={sx(q.x)} cy={sy(q.y)} r="6"><title>{q.l}: {q.x}, {q.y}</title></circle>)}<text x="370" y="605">{x}</text><text transform="translate(16 360) rotate(-90)">{y}</text></svg>}

export function TimeSeries({rows,date,metric}:{rows:Row[];date:string;metric:string}){if(!date||!metric)return <div className="empty">Choose date and metric.</div>;const g=new Map<string,number[]>();rows.forEach(r=>{const k=txt(r[date]),v=num(r[metric]);if(k&&v!==null){if(!g.has(k))g.set(k,[]);g.get(k)!.push(v)}});const p=[...g].map(([d,a])=>({d,v:a.reduce((s,x)=>s+x,0)/a.length})).sort((x,y)=>x.d.localeCompare(y.d,undefined,{numeric:true}));if(p.length<2)return <div className="empty">Need at least two periods.</div>;const a=Math.min(...p.map(q=>q.v)),b=Math.max(...p.map(q=>q.v)),sx=(i:number)=>55+i/(p.length-1||1)*650,sy=(v:number)=>540-(v-a)/(b-a||1)*450,dd=p.map((q,i)=>`${i?"L":"M"}${sx(i)},${sy(q.v)}`).join(" ");return <svg viewBox="0 0 760 600" className="timeviz"><path d={dd}/>{p.map((q,i)=><circle key={q.d} cx={sx(i)} cy={sy(q.v)} r="5"><title>{q.d}: {q.v.toLocaleString()}</title></circle>)}</svg>}

export function Distribution({rows,metric}:{rows:Row[];metric:string}){const v=rows.map(r=>num(r[metric])).filter((x):x is number=>x!==null);if(v.length<3)return <div className="empty">Need at least three observations.</div>;const a=Math.min(...v),b=Math.max(...v),k=10,w=(b-a||1)/k,c=new Array(k).fill(0);v.forEach(x=>c[Math.min(k-1,Math.floor((x-a)/(w||1)))]++);const m=Math.max(...c,1);return <div className="histviz">{c.map((x,i)=><div key={i}><i style={{height:`${Math.max(4,x/m*100)}%`}}/><span>{(a+i*w).toLocaleString(undefined,{maximumFractionDigits:1})}</span></div>)}</div>}

export function Quality({rows,matched,total,dup,issues,missing}:{rows:Row[];matched:number;total:number;dup:number;issues:string[];missing:{c:string;n:number;p:number}[]}){return <div className="qualityviz"><h3>Due diligence before design</h3><div><article><b>{rows.length}</b><span>observations</span></article><article><b>{matched}</b><span>boundaries matched</span></article><article><b>{Math.max(0,total-matched)}</b><span>unmatched boundaries</span></article><article><b>{dup}</b><span>duplicate keys</span></article></div><h4>Automatic flags</h4>{issues.length?issues.map((x,i)=><p key={i}>{x}</p>):<p>No major automatic flags. Human source verification is still required.</p>}<h4>Largest missing-value checks</h4>{missing.slice(0,6).map(x=><p key={x.c}><b>{x.c}</b>: {x.n} missing ({Math.round(x.p*100)}%)</p>)}</div>}
