import ReaderControls from "../../../components/ReaderControls";
import PriceGuaranteeExplorer from "../../../components/PriceGuaranteeExplorer";
export const metadata={title:"The price of a promise | Jamal Nasir",description:"What it would cost to fix Pakistan's wholesale electricity price for a year, and who pays when it goes wrong."};
export default function Page(){return <main className="promise"><style>{css}</style><ReaderControls articleKey="price-of-a-promise" articleTitle="The price of a promise"/><header><a href="/">Jamal Nasir</a><nav><a href="/">Research</a><a href="/editor">Editor</a></nav></header><article>
 <div className="hero"><div className="kicker">PAKISTAN POWER · PRODUCT STRUCTURING</div><div className="working">Work in progress</div><h1>The price of a promise</h1></div>
 <p className="deck">What it would cost to fix Pakistan's wholesale electricity price for a year, using the ISMO hourly demand and marginal-cost record, and who pays when it goes wrong.</p><p className="meta">By Jamal Nasir · Published 22 September 2026 · Data period: February 2024 to April 2026</p>
 <p className="lead">A fixed price sounds simple. A buyer pays one rate for every unit of electricity and stops worrying about the market. The market keeps moving anyway. Somebody still has to fund the difference.</p>
 <p>That difference can be measured from the hourly Pakistani system record. It rebuilds the contribution already in circulation, tests what happens when the year turns against the fund, and exposes a feature of the structure that is easy to miss: changing the headline price is not the strongest way to make the guarantee safer.</p>
 <aside><b>The central finding</b><span>Raising the fixed price is the intuitive way to make a guarantee safer. On this record it barely works: a 60% increase in the headline tariff reduces the guarantor's worst-year exposure by 22%. Prefunding the pool does what the price cannot. At 67% loading the pool absorbs the hardest twelve months in the record, but a 25% price shock still produces a PKR 4.75bn call on a 400MW book.</span></aside>
 <h2>The starting number survives reconstruction</h2>
 <p>The proposed structure begins with a pooled fund. Buyers contribute before the year starts. They pay a fixed electricity price, K. Whenever the wholesale price rises above K, the fund pays the positive difference. Once the fund is exhausted, the guarantor pays the remainder. Any surplus stays in the pool.</p>
 <p>One number was already in circulation: PKR 21.77m per average megawatt. Rebuilding the model from the hourly demand and marginal-cost tables returns PKR 21,769,591, a difference of roughly PKR 150. That is small enough to be rounding rather than a different economic model.</p>
 <h2>One hour shows how the guarantee actually pays</h2>
 <p>Take April 2025, hour 23:00. The system drew an average of 15,987.31 megawatts in that hour. A one-megawatt buyer's share is 15,987.31 ÷ 14,272, or 1,120.19 kilowatts. That hour occurs once a day for 30 days, so the buyer took 33,606 kilowatt-hours. The market price was 27.9811 rupees against a fixed price of 16.3503, a gap of 11.6308, and 33,606 × 11.6308 gives 390,862 rupees owed for that one hour-of-day across the month. Repeat it 288 times and the year costs 21,769,591 rupees per megawatt.</p>
 <p>In those cheap hours, nothing comes back. At midday in April the market sat at 14.22 while the buyer paid 16.35. The buyer overpaid by more than two rupees and the fund kept none of it.</p>
 <PriceGuaranteeExplorer/>
 <h2>There is only one clean pricing year</h2>
 <p>The record contains 26 months, from February 2024 through April 2026, with monthly profiles for each hour of the day. Only calendar 2025 is complete. December 2024 is absent from the record, and 2026 stops in April. That makes 2025 the pricing basis. The remaining months are useful for stress, but they do not create several independent years of evidence.</p>
 <div className="factgrid"><div><b>26</b><span>months in the record</span></div><div><b>1</b><span>complete calendar year</span></div><div><b>288</b><span>month-hour cells in the 2025 pricing year</span></div><div><b>8.76m</b><span>kWh for one average MW over a year</span></div></div>
 <p>Two data-quality issues should travel with every result. June and July 2024 are identical in both demand and price, and February 2026 reports implausibly low system demand. Neither changes the 2025 pricing basis, but both matter if the dataset is extended into a forecasting exercise.</p>
 <h2>The fixed price is not really an independent assumption</h2>
 <p>The 2025 load-weighted wholesale price is PKR 16.350335/kWh. The model's fixed price is PKR 16.3503. They are effectively the same number.</p>
 <p>That changes the interpretation. K is not a commercial margin sitting above the market. It is the observed year's own average cost, rounded. The guarantee therefore pays whenever the hourly market sits above that average, while receiving nothing when the market falls below it.</p>
 <blockquote>Protection is one-sided. Expensive hours create claims. Cheap hours do not refill the fund.</blockquote>
 <h2>The risk arrives after the sun goes down</h2>
 <p>The hourly pattern is more revealing than the annual average. 23:00 carries about PKR 2.68m of annual payouts per MW. At 13:00 the equivalent figure is about PKR 94,000. The ratio is roughly twenty-eight to one.</p>
 <p>This means timing can materially change the economics even when average megawatts are held constant. The interactive model includes load-shape sensitivity cases, but they are not claims about representative buyers. The national curve remains the base case, the buyer profile can be tested directly, and illustrative operating shapes are used only to expose sensitivity. An actual quote should be based on the buyer's own metered interval data.</p>
 <h2>A fund sized to the central year has almost no room for error</h2>
 <table><thead><tr><th>12-month period</th><th>Cost per MW (PKR m)</th><th>NCGCL pays (PKR m)</th></tr></thead><tbody><tr><td>Jan 2025 to Dec 2025</td><td>21.77</td><td>–</td></tr><tr><td>Feb 2025 to Jan 2026</td><td>23.99</td><td>2.22</td></tr><tr><td>Mar 2025 to Feb 2026</td><td>23.99</td><td>2.22</td></tr><tr><td>Apr 2025 to Mar 2026</td><td>24.18</td><td>2.41</td></tr><tr><td>May 2025 to Apr 2026</td><td>37.44</td><td>15.67</td></tr></tbody></table>
 <p className="caption">These windows overlap heavily. They are stress views of a short record, not five independent annual observations.</p>
 <p>The hardest window costs PKR 37.44m per MW. April 2026 does most of the damage, producing PKR 17.77m of payouts per MW in that month alone.</p>
 <h2>Charging a higher fixed price barely solves the capital problem</h2>
 <p>The intuitive response is to raise K. Claims fall when the fixed price rises, but the fund is also sized from those expected claims. The attachment point falls with the losses. Much of the apparent protection cancels out.</p>
 <table><thead><tr><th>Fixed price (PKR/kWh)</th><th>Buyer all-in (PKR/kWh)</th><th>NCGCL pays (PKR m)</th></tr></thead><tbody><tr><td>16.3503</td><td>18.72</td><td>15.46</td></tr><tr><td>18.00</td><td>19.67</td><td>15.01</td></tr><tr><td>20.00</td><td>20.98</td><td>14.57</td></tr><tr><td>22.00</td><td>22.48</td><td>14.12</td></tr><tr><td>26.00</td><td>26.07</td><td>11.99</td></tr></tbody></table>
 <p>Moving the fixed price from 16.35 to 26.00 raises the headline tariff by close to 60%, yet the modeled worst-year guarantor exposure falls by only about 22%.</p>
 <p>There is a tell in the last column. At a fixed price of 16.35 the guarantor pays 75% of the premium in a bad year. At 26.00 it pays 2,039%. The higher the price, the less pool there is, and the worse the structure becomes in relative terms.</p>
 <h2>Prefunding works differently</h2>
 <p>Loading the pool adds capital without simultaneously moving the strike. In the model cases, 67% loading is enough to absorb the hardest observed twelve-month window at K of 16.3503.</p>
 <table><thead><tr><th>Loading</th><th>Premium per MW (PKR m)</th><th>Buyer all-in (PKR/kWh)</th><th>NCGCL pays (PKR m)</th></tr></thead><tbody><tr><td>0%</td><td>20.72</td><td>18.72</td><td>15.46</td></tr><tr><td>25%</td><td>25.90</td><td>19.31</td><td>9.68</td></tr><tr><td>50%</td><td>31.08</td><td>19.90</td><td>3.90</td></tr><tr><td>67%</td><td>34.61</td><td>20.30</td><td>–</td></tr><tr><td>100%</td><td>41.45</td><td>21.08</td><td>–</td></tr></tbody></table>
 <p>The comparison is striking. A fixed price of 20.00 gives the buyer an all-in cost of 20.98 and still leaves PKR 14.57m per MW with the guarantor in the hardest year. Keeping K at 16.3503 and loading the fund to 67% gives an all-in price of 20.30 and removes that observed tail entirely.</p>
 <p>Which makes the buyer who refuses to prefund the dangerous one. No fixed price makes a zero-premium buyer safe. At 26.00 rupees with no pool at all, the guarantor still absorbs twelve million per megawatt in a bad year.</p>
 <h2>The payout curve is convex</h2>
 <p>A uniform 25% increase in prices does not require 25% more funding. The model says it needs 119% loading to keep the guarantor at zero. Existing positive gaps widen, while previously cheap hours cross above K and begin generating claims. The guarantee only pays one side of the distribution, so the funding requirement accelerates as prices rise.</p>
 <h2>At 400MW, the tail becomes a balance-sheet question</h2>
 <p>At K of 16.3503, 67% loading and an 11% annual fund return, the 400MW case requires about PKR 13.84bn upfront.</p>
 <table><thead><tr><th>Scenario</th><th>Payouts (PKR bn)</th><th>Fund pays (PKR bn)</th><th>NCGCL pays (PKR bn)</th></tr></thead><tbody><tr><td>2025 repeats</td><td>8.71</td><td>8.71</td><td>–</td></tr><tr><td>Prices 10% higher</td><td>12.59</td><td>12.59</td><td>–</td></tr><tr><td>Prices 25% higher</td><td>19.17</td><td>14.42</td><td>4.75</td></tr><tr><td>Prices 50% higher</td><td>31.34</td><td>14.25</td><td>17.09</td></tr><tr><td>Worst year on record</td><td>14.98</td><td>14.98</td><td>–</td></tr></tbody></table>
 <p>That is where product design stops being a pricing exercise. PKR 4.75bn at a 25% price shock and PKR 17.09bn at a 50% shock need an explicit answer about who holds the capital. An uncapped guarantee is not made safe merely because the central case looks funded.</p>
 <h2>The surplus changes the economics of later cohorts</h2>
 <p>In a repeat of 2025, the 67% loaded pool finishes with about PKR 6.20bn at 400MW. If the surplus is retained, the product is not resetting to zero each year. The first cohort is capitalising a buffer for later cohorts.</p>
 <p>One natural assumption does not hold. Pooling across buyers spreads differences between buyers. It does nothing here, because the risk is not idiosyncratic. When April 2026 arrives, every buyer is short at the same moment. A hundred buyers in one pool are exactly as exposed, per megawatt, as one.</p>
 <p>That points toward a declining loading structure rather than a permanent surcharge: higher at launch when the pool has no retained capital, lower as the buffer builds. The exact step-down rule still needs governance, liquidity and treasury treatment.</p>
 <h2>What the model does not know</h2>
 <p>The evidence is short. Buyer load shapes are not yet observed. The 11% fund return is an assumption, not a committed treasury rate. Credit risk, administration, guarantee fees and the guarantor's own cost of capital sit outside the calculation. A 400MW book may also alter the market it is being priced against, which cannot be quantified without generation-stack data.</p>
 <p>Most importantly, the price shocks in the simulator are simple proportional shifts. Real shocks are not uniform. An evening-heavy shock could cost much more than another shock with the same annual average.</p>
 <h2>The design choice</h2>
 <p>The model supports a clearer product conversation. Set K deliberately. Price by load shape. Capitalise the pool above the central case. Retain surplus under an explicit rule. Put a cap, co-payment or committed capital line around the tail. And keep the short history visible rather than turning overlapping windows into false probabilities.</p>
 <div className="method"><span>REPRODUCIBILITY</span><h3>Three operations rebuild the model</h3><ol><li>Scale system demand into the buyer's electricity for each month and hour.</li><li>Multiply that electricity by max(market price minus K, zero).</li><li>Size the starting pool as the NPV of the twelve monthly payouts at the pool's monthly earning rate, then apply the chosen loading.</li></ol><h4>Working files</h4><p className="workingFile"><a href="https://pern-my.sharepoint.com/:x:/g/personal/25250023_lums_edu_pk/IQAbnYwbVqgtTp5pBwhrlHbRATkt6M58WbvOGwxtrjPzYHQ">Working spreadsheet (XLSX)</a> — the same model in live Excel formulas, with the full hourly working in a collapsed block.</p><p className="workingFile"><a href="https://pern-my.sharepoint.com/:u:/g/personal/25250023_lums_edu_pk/IQD0PQ0WN2g4RY3iVKYCJuDXAeVay10PUktl_2_9qLgnacY">Python notebook (IPYNB)</a> — the analysis as originally run, cell by cell, from reading the ISMO tables to the loading and scenario sweeps.</p><p>The spreadsheet, the notebook and the simulation on this page are three independent implementations of the same three operations. They agree to the paisa.</p><p className="source">Source: ISMO hourly system demand and marginal cost, February 2024 to April 2026.</p></div>
 </article></main>}
const css=`
.promise{--chrome:#1A3C5A;min-height:100vh;background:var(--reader-bg,#f7f1e8);color:var(--reader-text,#202426)}.promise>header{height:64px;border-bottom:1px solid var(--chrome);display:flex;justify-content:space-between;align-items:center;padding:0 28px;font-family:Arial}.promise>header a{color:var(--reader-ink,#202426);text-decoration:none;font-weight:700}.promise nav{display:flex;gap:20px}.promise article{width:min(1040px,calc(100% - 36px));margin:auto;padding:68px 0 100px;font:var(--reader-size,19px)/1.72 var(--reader-font,Georgia,serif)}.promise article>p,.promise article>h2,.promise article>blockquote,.promise article>aside,.promise article>table,.promise article>.caption,.promise article>.method,.hero{max-width:var(--reader-width,790px);margin-left:auto;margin-right:auto}.kicker{font:900 10px Arial;letter-spacing:.14em;color:var(--chrome)}.working{width:max-content;margin:12px 0 0;padding:5px 7px;border:1px solid var(--chrome);color:var(--chrome);font:800 9px Arial;letter-spacing:.09em;text-transform:uppercase}.promise h1{margin:12px 0;font:700 clamp(54px,7vw,88px)/.93 var(--reader-font,Georgia,serif);letter-spacing:-.045em;color:var(--reader-ink,#202426)}.deck{font-size:1.25em;line-height:1.4;color:var(--reader-muted,#5c6265)}.meta{font:11px Arial;color:var(--reader-muted,#5c6265);border-bottom:1px solid var(--chrome);padding-bottom:24px}.lead{font-size:1.2em}.promise h2{font:700 1.8em/1.08 var(--reader-font,Georgia,serif);margin-top:2em;color:var(--reader-ink,#202426)}.promise aside{border-top:3px solid var(--chrome);border-bottom:1px solid var(--chrome);padding:16px 0;margin-top:32px}.promise aside b{font:900 9px Arial;letter-spacing:.12em;color:var(--chrome)}.promise aside span{display:block;font:700 21px/1.35 var(--reader-font,Georgia,serif);margin-top:6px}.promise blockquote{border-left:3px solid var(--chrome);padding-left:18px;font-style:italic}.factgrid{max-width:900px;margin:34px auto;display:grid;grid-template-columns:repeat(4,1fr);border-block:1px solid var(--chrome)}.factgrid div{padding:16px;border-right:1px solid var(--reader-line,#d8d4cd)}.factgrid b{display:block;font:700 30px var(--reader-font,Georgia,serif)}.factgrid span{font:9px/1.4 Arial;color:var(--reader-muted,#5c6265)}
.promise table{width:min(var(--reader-width,790px),100%);border-collapse:collapse;font:12px/1.35 Arial;margin-top:24px;border-top:1px solid var(--chrome);border-bottom:1px solid var(--chrome);font-variant-numeric:tabular-nums}.promise th,.promise td{padding:10px;border-bottom:.5px solid var(--reader-line,#d8d4cd)}.promise th{font-size:8px;text-transform:uppercase;letter-spacing:.06em;color:var(--reader-muted,#5c6265);text-align:right}.promise td{text-align:right}.promise th:first-child,.promise td:first-child{text-align:left}.promise tbody tr:last-child td{border-bottom:0}.caption{font:italic 11px/1.45 Arial;color:var(--reader-muted,#5c6265)}.method{margin-top:50px;border-top:4px solid var(--chrome);padding-top:18px}.method>span{font:900 9px Arial;letter-spacing:.13em;color:var(--chrome)}.method h3{font:700 28px/1.1 var(--reader-font,Georgia,serif);margin:6px 0}.method ol{padding:0;margin:18px 0 26px;list-style-position:inside}.method li{margin:0 0 10px;font:inherit}.method h4{font:700 18px/1.2 var(--reader-font,Georgia,serif);margin:24px 0 8px}.workingFile{font:14px/1.55 Arial}.workingFile a{color:var(--chrome);font-weight:800;text-underline-offset:3px}.source{font:10px/1.5 Arial;color:var(--reader-muted,#5c6265)}
@media(max-width:760px){.factgrid{grid-template-columns:1fr 1fr}.promise article{padding-top:44px}.promise h1{font-size:52px}}
@media print{.promise{--chrome:#1A3C5A;background:#fff;-webkit-print-color-adjust:exact;print-color-adjust:exact}.promise>header{display:none}.promise article{width:100%;padding:20px 0}.promise table,.promise aside,.factgrid,.method{break-inside:avoid}}
`;
