import ResearchPulse from "../components/ResearchPulse";

const research=[
 {href:"/article/precision-recall-text-summarization",section:"Explainable AI",kicker:"NLP · Model evaluation",title:"Precision and Recall in Text Summarization: Why Bigrams Matter",deck:"Why unigram precision and recall can reward the wrong summary, and how bigrams preserve more of the sequence.",meta:"Latest · Mar 2025"},
 {href:"/article/pakistan-power-transition",section:"Power & Energy",kicker:"Pakistan power · Structural analysis",title:"Pakistan built for electricity scarcity. Now the grid is losing demand.",deck:"Excess capacity, distributed solar, fixed costs and transmission are reshaping the country's power crisis.",meta:"Structural analysis"},
 {href:"/article/pakistan-food-export-intelligence",section:"Economics",kicker:"Pakistan trade · Interactive",title:"Where Pakistan’s export strength really sits.",deck:"A chapter-by-chapter reading of exporter concentration, product mix and strategically important capabilities.",meta:"Export intelligence · HS 01–24"},
 {href:"/article/visual-intelligence-benchmark",section:"Tech",kicker:"Visual research · Product benchmark",title:"When the map becomes the argument.",deck:"A compact benchmark for linked maps, derived metrics and visual-first research publishing.",meta:"Visual intelligence"}
];
const sections=["All","Tech","Explainable AI","Power & Energy","Economics"];

const homeStyles=`.compact-identity{min-height:auto;padding:64px 0 76px;border-top:1px solid #d8d4cd}.compact-identity h1{max-width:860px;font-size:clamp(48px,6vw,76px)}.notes-section{padding:46px 0 66px}.notes-label{margin-bottom:14px;color:#6d7375;font-size:11px;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.section-nav{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 20px}.section-nav a{padding:7px 10px;border:1px solid #d8d4cd;font:700 10px Arial,sans-serif;color:#555d60;text-decoration:none}.section-nav a:first-child{background:#202426;color:#fff;border-color:#202426}.research-list{border-top:4px solid #202426}.research-row{display:grid;grid-template-columns:minmax(0,1fr) 230px;gap:42px;padding:26px 0 28px;border-bottom:1px solid #d8d4cd;text-decoration:none}.research-copy .kicker{font-size:10px;font-weight:800;letter-spacing:.12em;text-transform:uppercase;color:#004d73}.research-copy h2{margin:8px 0 10px;max-width:900px;font:700 clamp(28px,3.2vw,46px)/1.03 Georgia,'Times New Roman',serif;letter-spacing:-.03em;color:#202426}.research-copy p{max-width:760px;margin:0;font:17px/1.5 Georgia,'Times New Roman',serif;color:#555d60}.research-meta{border-left:1px solid #d8d4cd;padding-left:24px;display:flex;flex-direction:column;gap:7px;align-items:flex-start;font-size:10px;line-height:1.5;font-weight:800;letter-spacing:.07em;text-transform:uppercase;color:#6d7375}.research-meta b{color:#004d73}.research-row:hover h2{color:#004d73}.feedback{display:flex;justify-content:space-between;gap:24px;align-items:center;padding:24px 0 44px;border-bottom:1px solid #d8d4cd}.feedback span{font:700 12px Arial,sans-serif;letter-spacing:.12em;color:#004d73;text-transform:uppercase}.feedback a{font:18px Georgia,serif;border-bottom:1px solid #202426;padding-bottom:3px}.toplinks{display:flex;gap:18px;font-size:13px;color:#6d7375}.toplinks a:hover{color:#004d73}@media(max-width:760px){.research-row{grid-template-columns:1fr;gap:12px}.research-meta{border-left:0;padding-left:0}.compact-identity{padding-top:52px}.feedback{align-items:flex-start;flex-direction:column}.toplinks{gap:12px}.research-copy h2{font-size:30px}}`;

export default function HomePage(){return <main className="public-home"><style>{homeStyles}</style><ResearchPulse/><div className="shell"><header className="topbar home-topbar"><a className="brand" href="/"><strong>Jamal Nasir</strong></a><nav className="toplinks"><a href="#latest">Latest research</a><a href="mailto:j.nasir25260@gmail.com?subject=Feedback%20on%20your%20research">Feedback</a><a href="/editor">Editor</a></nav></header><section id="latest" className="notes-section"><div className="notes-label">Published research</div><nav className="section-nav" aria-label="Research sections">{sections.map(s=><a href={s==="All"?"#latest":`#${s.toLowerCase().replace(/[^a-z]+/g,"-")}`} key={s}>{s}</a>)}</nav><div className="research-list">{research.map((r,i)=><a className="research-row" id={r.section.toLowerCase().replace(/[^a-z]+/g,"-")} href={r.href} key={r.href}><div className="research-copy"><span className="kicker">{i===0?"Latest · ":""}{r.kicker}</span><h2>{r.title}</h2><p>{r.deck}</p></div><div className="research-meta"><b>{r.section}</b><span>{r.meta}</span></div></a>)}</div></section><section className="identity-hero compact-identity"><h1>Enthusiastic to build and create.</h1><p className="identity-line">Quantifying economic signals for a sustainable future.</p><p className="identity-copy">I work across research, data, finance and systems, turning complex evidence into useful analysis, tools and ideas that can be tested, improved and put to work.</p></section><section className="feedback"><span>Feedback and collaboration</span><a href="mailto:j.nasir25260@gmail.com">j.nasir25260@gmail.com</a></section></div></main>}
