"use client";
import {useState} from "react";
const scenarios=[["2025 repeats",8.71,0,6.20],["Prices 10% higher",12.59,0,2.10],["Prices 25% higher",19.17,4.75,0],["Prices 50% higher",31.34,17.09,0],["Worst year on record",14.98,0,0]];
const loads=[[0,20.7,18.72,15.46],[25,25.9,19.31,9.68],[50,31.1,19.90,3.90],[67,34.6,20.30,0],[100,41.4,21.08,0]];
const fixed=[[16.3503,18.72,15.46],[18,19.67,15.01],[20,20.98,14.57],[22,22.48,14.12],[26,26.07,11.99]];
const hours=[.76,.61,.57,.45,.49,.72,1.31,1.45,1.47,1.15,.78,.31,.18,.094,.31,.79,1.33,1.75,1.69,1.72,2.05,2.18,2.34,2.68];
export default function PriceGuaranteeExplorer(){
 const[book,setBook]=useState(400),[si,setSi]=useState(2),[li,setLi]=useState(3),[ki,setKi]=useState(0);
 const s=scenarios[si],l=loads[li],k=fixed[ki],scale=book/400,max=Math.max(...hours);
 const bn=(v:number)=>(v*scale).toFixed(2)+"bn";
 return <section className="pgx">
  <div className="pgTop"><div><span>LIVE STRUCTURE</span><h2>Change the assumptions. Watch who pays.</h2></div><p>Each control is anchored to a case in the supplied model. Book size scales linearly. Nothing here is a forecast.</p></div>
  <div className="pgControls"><label>Book size<input type="range" min="50" max="800" step="50" value={book} onChange={e=>setBook(+e.target.value)}/><b>{book} MW</b></label><label>Price scenario<select value={si} onChange={e=>setSi(+e.target.value)}>{scenarios.map((x,i)=><option value={i} key={String(x[0])}>{x[0]}</option>)}</select></label></div>
  <div className="pgKpis"><div><span>Buyers prefund</span><b>PKR {(13.84*(Number(l[1])/34.6)*scale).toFixed(2)}bn</b></div><div><span>Scenario payouts</span><b>PKR {bn(Number(s[1]))}</b></div><div><span>Guarantor pays</span><b>PKR {bn(Number(s[2]))}</b></div><div><span>Pool left</span><b>PKR {bn(Number(s[3]))}</b></div></div>
  <div className="pgGrid"><div className="pgPanel"><span>PRICE STRESS</span><h3>The tail appears quickly</h3>{scenarios.map((x,i)=><button className={si===i?"on":""} onClick={()=>setSi(i)} key={String(x[0])}><em>{x[0]}</em><i style={{width:(Number(x[1])/31.34*100)+"%"}}/><b>{Number(x[2]).toFixed(2)}bn</b></button>)}</div>
  <div className="pgPanel"><span>TIME OF DAY</span><h3>This is a night-time product</h3><div className="pgHours">{hours.map((v,h)=><div title={String(h).padStart(2,"0")+":00 | PKR "+v.toFixed(2)+"m per MW"} key={h}><i style={{height:(v/max*100)+"%"}}/><small>{h%3===0?String(h).padStart(2,"0"):""}</small></div>)}</div><p>23:00 carries about PKR 2.68m of annual payouts per MW. At 13:00 it is about PKR 0.094m.</p></div></div>
  <div className="pgGrid"><div className="pgPanel"><span>FIXED PRICE</span><h3>Raising K is a weak safety lever</h3><select value={ki} onChange={e=>setKi(+e.target.value)}>{fixed.map((x,i)=><option value={i} key={i}>K = {Number(x[0]).toFixed(i===0?4:2)}</option>)}</select><strong>{Number(k[1]).toFixed(2)} <small>PKR/kWh all-in</small></strong><p>Worst-year guarantor: PKR {(Number(k[2])*book).toFixed(0)}m at {book} MW.</p></div>
  <div className="pgPanel"><span>POOL LOADING</span><h3>Prefunding changes the tail directly</h3><select value={li} onChange={e=>setLi(+e.target.value)}>{loads.map((x,i)=><option value={i} key={i}>{x[0]}% loading</option>)}</select><strong>{Number(l[2]).toFixed(2)} <small>PKR/kWh all-in</small></strong><p>Worst-year guarantor: PKR {(Number(l[3])*book).toFixed(0)}m at {book} MW.</p></div></div>
  <div className="pgTable"><span>CONVEXITY</span><h3>A quarter dearer needs more than twice the central fund</h3><table><thead><tr><th>If prices run</th><th>Loading for zero guarantor</th><th>All-in</th></tr></thead><tbody><tr><td>as 2025 did</td><td>0%</td><td>18.72</td></tr><tr><td>10% higher</td><td>44%</td><td>19.76</td></tr><tr><td>25% higher</td><td>119%</td><td>21.54</td></tr><tr><td>50% higher</td><td>258%</td><td>24.82</td></tr><tr><td>100% higher</td><td>560%</td><td>31.96</td></tr></tbody></table></div>
 </section>
}
const css=".pgx{margin:50px 0;border-top:4px solid var(--reader-ink,#202426);padding-top:18px;font-family:Arial}.pgTop{display:grid;grid-template-columns:1.2fr .8fr;gap:24px}.pgTop span,.pgPanel>span,.pgTable>span{font-size:9px;font-weight:900;letter-spacing:.14em;color:var(--reader-brand,#004d73)}.pgTop h2{font:700 34px/1.03 var(--reader-font,Georgia,serif);margin:6px 0}.pgTop p,.pgPanel p{font:11px/1.5 Arial;color:var(--reader-muted,#6d7375)}.pgControls{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:22px 0}.pgControls label{font-size:9px;font-weight:800;text-transform:uppercase;letter-spacing:.08em}.pgControls input{width:70%;margin:0 10px}.pgControls select,.pgPanel select{width:100%;padding:9px;border:1px solid var(--reader-line,#d8d4cd);background:var(--reader-surface,#fbf8f3);color:inherit}.pgKpis{display:grid;grid-template-columns:repeat(4,1fr);border-block:1px solid var(--reader-line,#d8d4cd)}.pgKpis div{padding:14px;border-right:1px solid var(--reader-line,#d8d4cd)}.pgKpis span{display:block;font-size:8px;text-transform:uppercase;color:var(--reader-muted,#6d7375)}.pgKpis b{display:block;font:700 23px var(--reader-font,Georgia,serif);margin-top:5px}.pgGrid{display:grid;grid-template-columns:1fr 1fr;gap:15px;margin-top:15px}.pgPanel,.pgTable{border:1px solid var(--reader-line,#d8d4cd);padding:15px;background:var(--reader-surface,#fbf8f3)}.pgPanel h3,.pgTable h3{font:700 19px/1.1 var(--reader-font,Georgia,serif);margin:5px 0 14px}.pgPanel button{display:grid;grid-template-columns:1fr 90px 60px;gap:7px;align-items:center;width:100%;border:0;border-top:1px solid var(--reader-line,#d8d4cd);padding:9px 0;background:transparent;color:inherit;text-align:left;font-size:9px}.pgPanel button em{font-style:normal}.pgPanel button i{height:7px;background:var(--reader-brand,#004d73)}.pgPanel button.on em{font-weight:900}.pgPanel button b{text-align:right}.pgHours{height:145px;display:flex;gap:3px;align-items:flex-end;border-bottom:1px solid var(--reader-line,#d8d4cd)}.pgHours div{height:100%;flex:1;display:flex;flex-direction:column;justify-content:flex-end}.pgHours i{width:100%;background:var(--reader-brand,#004d73);opacity:.8}.pgHours small{height:13px;font-size:7px;text-align:center}.pgPanel strong{display:block;font:700 34px var(--reader-font,Georgia,serif);margin:18px 0}.pgPanel strong small{font:10px Arial;color:var(--reader-muted,#6d7375)}.pgTable{margin-top:15px}.pgTable table{width:100%;border-collapse:collapse;font-size:11px}.pgTable th,.pgTable td{text-align:left;padding:9px;border-top:1px solid var(--reader-line,#d8d4cd)}.pgTable th{font-size:8px;text-transform:uppercase}@media(max-width:760px){.pgTop,.pgGrid,.pgControls{grid-template-columns:1fr}.pgKpis{grid-template-columns:1fr 1fr}}";
PriceGuaranteeExplorer.styles=css;
