"use client";
import {useMemo,useState} from "react";
import {runIsmoModel,type LoadShape} from "../lib/ismo-model";

const scenarios=[["2025 repeats",1],["Prices 10% higher",1.1],["Prices 25% higher",1.25],["Prices 50% higher",1.5],["Prices 100% higher",2]] as const;
const POOL="var(--pool)",GUARANTOR="var(--guarantor)";
const bn=(v:number)=>v/1e9,dash=(v:number,d=2)=>Math.abs(v)<1e-10?"–":v.toFixed(d),pct=(v:number,b:number)=>b?((v/b-1)*100):0;
const money=(v:number)=>Math.abs(v)<.5?"Nil":v>=1e9?"PKR "+bn(v).toFixed(2)+"bn":"PKR "+(v/1e6).toFixed(2)+"m";

function axis(max:number,target=4){
 const raw=Math.max(max,1e-9)/target,pow=10**Math.floor(Math.log10(raw)),q=raw/pow;
 const step=([1,2,2.5,5,10].find(x=>x>=q)||10)*pow;
 const top=Math.ceil(max/step)*step,dec=step>=1?0:step>=.1?1:2;
 return{step,top,dec,values:Array.from({length:Math.round(top/step)+1},(_,i)=>i*step)};
}
function Legend({items}:{items:[string,string][]}){
 if(!items.length)return null;
 return <div className="legend">{items.map(([label,color])=><span className="legendItem" key={label}><svg width="10" height="10" viewBox="0 0 10 10" aria-hidden="true"><rect width="10" height="10" fill={color}/></svg><span>{label}</span></span>)}</div>;
}
function Footer({line}:{line:string}){return <div className="chartFooter"><span>{line}</span><span>Source: ISMO hourly demand and marginal cost, calendar 2025.</span></div>}
function Grid({a,W,L,R,T,ph}:{a:ReturnType<typeof axis>,W:number,L:number,R:number,T:number,ph:number}){
 return <>{a.values.map(v=>{const y=T+ph-v/a.top*ph;return <g key={v}><line x1={L} x2={W-R} y1={y} y2={y} className={v===0?"gridline zero":"gridline"}/><text x={L-8} y={y+3} textAnchor="end">{v.toFixed(a.dec)}</text></g>})}<line x1={L} x2={L} y1={T} y2={T+ph} className="axisline"/></>;
}

function MonthlyClaims({m,a}:{m:ReturnType<typeof runIsmoModel>,a:ReturnType<typeof axis>}){
 const W=620,H=235,L=52,R=14,T=25,B=32,pw=W-L-R,ph=H-T-B,g=pw/12,bw=Math.min(13,g*.28);
 return <div className="chart"><div className="unit">PKR bn</div><svg viewBox={"0 0 "+W+" "+H} role="img" aria-label="Monthly pool and NCGCL claims"><Grid a={a} W={W} L={L} R={R} T={T} ph={ph}/>{m.monthly.map((x,i)=>{const cx=L+g*(i+.5),p=bn(x.poolPays),n=bn(x.ncgcl);return <g key={x.month}><rect x={cx-bw-1} y={T+ph-p/a.top*ph} width={bw} height={p/a.top*ph} fill={POOL}/>{n>0&&<rect x={cx+1} y={T+ph-n/a.top*ph} width={bw} height={n/a.top*ph} fill={GUARANTOR}/>}<text x={cx} y={H-10} textAnchor="middle">{x.month.slice(0,3)}</text></g>})}</svg><Legend items={[["Pool pays",POOL],["NCGCL pays",GUARANTOR]]}/><Footer line="Monthly guarantee claims, PKR bn."/></div>;
}
function HourlyClaims({m,a}:{m:ReturnType<typeof runIsmoModel>,a:ReturnType<typeof axis>}){
 const W=620,H=235,L=52,R=14,T=25,B=32,pw=W-L-R,ph=H-T-B,g=pw/24,bw=Math.max(4,g*.62),vals=m.hourly.map(bn),peak=vals.indexOf(Math.max(...vals));
 return <div className="chart"><div className="unit">PKR bn</div><svg viewBox={"0 0 "+W+" "+H} role="img" aria-label="Guarantee payout by hour of day"><Grid a={a} W={W} L={L} R={R} T={T} ph={ph}/>{vals.map((v,h)=>{const x=L+g*(h+.5)-bw/2;return <g key={h}><rect x={x} y={T+ph-v/a.top*ph} width={bw} height={v/a.top*ph} fill={POOL} opacity={h===peak?1:.55}/>{h%3===0&&<text x={x+bw/2} y={H-10} textAnchor="middle">{String(h).padStart(2,"0")}</text>}</g>})}</svg><Legend items={[["Guarantee payout",POOL]]}/><Footer line="Annual guarantee payout grouped by hour of day, PKR bn."/></div>;
}
function PoolBalance({m}:{m:ReturnType<typeof runIsmoModel>}){
 const W=760,H=245,L=52,R=14,T=25,B=32,vals=[m.premium,...m.monthly.map(x=>x.end)].map(bn),a=axis(Math.max(...vals),3),pw=W-L-R,ph=H-T-B,pts=vals.map((v,i)=>[L+pw*i/12,T+ph-v/a.top*ph]),line=pts.map(p=>p.join(",")).join(" "),area=L+","+(T+ph)+" "+line+" "+(W-R)+","+(T+ph),empty=m.monthly.findIndex(x=>x.ncgcl>0);
 return <div className="chart"><div className="unit">PKR bn</div><svg viewBox={"0 0 "+W+" "+H} role="img" aria-label="Pool balance across the year"><Grid a={a} W={W} L={L} R={R} T={T} ph={ph}/><polygon points={area} fill={POOL} opacity=".10"/><polyline points={line} fill="none" stroke={POOL} strokeWidth="2"/>{empty>=0&&(()=>{const x=L+pw*(empty+1)/12;return <g><line x1={x} x2={x} y1={T} y2={T+ph} stroke={GUARANTOR} strokeDasharray="5 4"/><text className="markerLabel" x={Math.min(x+6,W-115)} y={T+12}>pool empties · {m.monthly[empty].month.slice(0,3)}</text></g>})()}{m.monthly.map((x,i)=><text key={x.month} x={L+pw*(i+1)/12} y={H-10} textAnchor="middle">{x.month.slice(0,3)}</text>)}</svg><Legend items={empty>=0?[["Pool balance",POOL],["Pool exhaustion",GUARANTOR]]:[["Pool balance",POOL]]}/><Footer line="Closing pool balance through the year, PKR bn."/></div>;
}
function LoadShapeChart({national,day,continuous}:{national:ReturnType<typeof runIsmoModel>,day:ReturnType<typeof runIsmoModel>,continuous:ReturnType<typeof runIsmoModel>}){
 const rows=[["National",bn(national.expected)],["Day shift",bn(day.expected)],["Continuous",bn(continuous.expected)]] as const,max=Math.max(...rows.map(x=>x[1]));
 return <div className="shapeChart"><div className="unit">PKR bn</div><div className="shapeRows">{rows.map(([name,v])=>{const delta=pct(v,rows[0][1]),label=name==="National"?"base":(delta>=0?"+":"")+delta.toFixed(0)+"%";return <div className="shapeRow" key={name}><span className="shapeName">{name}</span><svg className="shapeBar" viewBox="0 0 100 14" preserveAspectRatio="none" aria-hidden="true"><rect x="0" y="1" width={v/max*100} height="12" fill={POOL}/></svg><span className="shapeValue">{v.toFixed(2)} <em>{label}</em></span></div>})}</div><Legend items={[["Expected guarantee cost",POOL]]}/><Footer line="Expected guarantee cost by illustrative load shape, PKR bn."/></div>;
}

export default function PriceGuaranteeExplorer(){
 const[book,setBook]=useState(400),[K,setK]=useState(16.3503),[loading,setLoading]=useState(.67),[ret,setRet]=useState(.11),[mult,setMult]=useState(1),[shape,setShape]=useState<LoadShape>("national");
 const m=useMemo(()=>runIsmoModel(book,K,loading,ret,mult,shape),[book,K,loading,ret,mult,shape]),national=useMemo(()=>runIsmoModel(book,K,loading,ret,mult,"national"),[book,K,loading,ret,mult]),day=useMemo(()=>runIsmoModel(book,K,loading,ret,mult,"day-shift"),[book,K,loading,ret,mult]),continuous=useMemo(()=>runIsmoModel(book,K,loading,ret,mult,"continuous"),[book,K,loading,ret,mult]);
 const scenario=scenarios.find(x=>x[1]===mult)?.[0]||"Custom",totalDays=m.monthly.reduce((s,x)=>s+x.days,0),totP=m.monthly.reduce((s,x)=>s+x.payout,0),totI=m.monthly.reduce((s,x)=>s+x.interest,0),totPool=m.monthly.reduce((s,x)=>s+x.poolPays,0),totN=m.monthly.reduce((s,x)=>s+x.ncgcl,0),totUnits=m.monthly.reduce((s,x)=>s+x.electricity,0),weightedAvg=m.monthly.reduce((s,x)=>s+x.avgPrice*x.electricity,0)/totUnits,sharedAxis=axis(Math.max(...m.monthly.flatMap(x=>[bn(x.poolPays),bn(x.ncgcl)]),...m.hourly.map(bn)),4);
 return <section className="pgx"><style>{css}</style>
  <div className="top"><span>LIVE MODEL</span><h2>Change the contract. Recalculate the year.</h2><p>The model runs all 288 month-hour cells from the 2025 ISMO demand and marginal-cost tables. Book size, K, loading, fund return, price path and load shape feed the same calculation.</p></div>
  <div className="controls">
   <div className="controlGroup">
    <label>Book size<div className="typed"><input type="number" min="1" step="1" value={book} onChange={e=>setBook(Math.max(1,+e.target.value||1))}/><span className="rawUnit">MW</span></div></label>
    <label>Fixed price K<input className="number" type="number" min="0" step=".0001" value={K.toFixed(4)} onChange={e=>{if(e.target.value!=="")setK(+e.target.value)}}/></label>
    <label>Buyer load shape<select value={shape} onChange={e=>setShape(e.target.value as LoadShape)}><option value="national">National curve</option><option value="buyer-template">Attached buyer profile</option><option value="day-shift">Illustrative day shift</option><option value="continuous">Illustrative continuous</option></select></label>
   </div>
   <div className="controlGroup stressGroup">
    <label>Pool loading<div className="dual"><div className="typed"><input type="number" min="0" max="200" step="1" value={(loading*100).toFixed(0)} onChange={e=>setLoading(Math.max(0,+e.target.value||0)/100)}/><span className="rawUnit">%</span></div><input type="range" min="0" max="200" step="1" value={loading*100} onChange={e=>setLoading(+e.target.value/100)}/></div></label>
    <label>Fund return<div className="dual"><div className="typed"><input type="number" min="0" max="100" step=".25" value={(ret*100).toFixed(2)} onChange={e=>setRet(Math.max(0,+e.target.value||0)/100)}/><span className="rawUnit">%</span></div><input type="range" min="0" max="20" step=".25" value={ret*100} onChange={e=>setRet(+e.target.value/100)}/></div></label>
    <label>Price path<select value={mult} onChange={e=>setMult(+e.target.value)}>{scenarios.map(x=><option value={x[1]} key={x[0]}>{x[0]}</option>)}</select></label>
   </div>
  </div>
  <div className="kpis"><div><span>Buyer contribution</span><b>{money(m.premium)}</b><small>{m.premiumPerKwh.toFixed(2)} PKR/kWh</small></div><div><span>All-in price</span><b>{(Math.round(m.allIn*1000)/1000).toFixed(4)}</b><small>PKR per kWh, before fees</small></div><div><span>NCGCL exposure</span><b>{money(m.ncgcl)}</b><small>{m.ncgcl>0?"pool exhausts":"pool absorbs year"}</small></div><div><span>Closing pool</span><b>{money(m.surplus)}</b><small>retained buffer</small></div></div>
  <div className="callout"><span>MODEL READOUT</span><b>{m.ncgcl>0?"The pool runs out. NCGCL takes the remaining "+money(m.ncgcl).replace("PKR ","")+" of claims.":"The selected structure absorbs the full scenario without calling NCGCL."}</b></div>
  <div className="grid"><div className="panel"><span>MONTHLY DRAWDOWN</span><h3>Claims move through the pool first</h3><MonthlyClaims m={m} a={sharedAxis}/></div><div className="panel"><span>HOUR OF DAY</span><h3>Which hours create the annual claim</h3><HourlyClaims m={m} a={sharedAxis}/></div></div>
  <div className="panel poolPanel"><span>POOL BALANCE</span><h3>Watch the fund meet the year</h3><PoolBalance m={m}/></div>
  <div className="shapeNote"><b>Load-shape sensitivity, not buyer classification.</b> The national curve remains the base case. The attached buyer profile uses the 12 × 24 values provided with this research. Day-shift and continuous profiles are illustrative bounding scenarios only. They are not representative buyers, probabilities or empirical findings. Actual pricing should use the buyer’s own metered interval data.</div>
  <LoadShapeChart national={national} day={day} continuous={continuous}/>
  <div className="table"><div><span>MONTH BY MONTH</span><h3>Every displayed number comes from the same live calculation</h3><p className="scenarioLine">Showing: {scenario} · book {book} MW · K {K.toFixed(4)} · loading {(loading*100).toFixed(0)}%</p></div><table><thead><tr><th>Month</th><th>Days</th><th>Avg market<br/><span className="rawUnit">(PKR/kWh)</span></th><th>Payout<br/><span className="rawUnit">(PKR bn)</span></th><th>Interest earned<br/><span className="rawUnit">(PKR bn)</span></th><th>Pool pays<br/><span className="rawUnit">(PKR bn)</span></th><th>NCGCL pays<br/><span className="rawUnit">(PKR bn)</span></th><th>Pool closes<br/><span className="rawUnit">(PKR bn)</span></th></tr></thead><tbody><tr className="opening"><td>Opening pool</td><td>–</td><td>–</td><td>–</td><td>–</td><td>–</td><td>–</td><td>{bn(m.premium).toFixed(2)}</td></tr>{m.monthly.map(x=><tr key={x.month}><td>{x.month}</td><td>{x.days}</td><td>{x.avgPrice.toFixed(2)}</td><td>{dash(bn(x.payout))}</td><td>{dash(bn(x.interest))}</td><td>{dash(bn(x.poolPays))}</td><td>{dash(bn(x.ncgcl))}</td><td>{dash(bn(x.end))}</td></tr>)}<tr className="total"><td>Total</td><td>{totalDays}</td><td>{weightedAvg.toFixed(4)}</td><td>{dash(bn(totP))}</td><td>{dash(bn(totI))}</td><td>{dash(bn(totPool))}</td><td>{dash(bn(totN))}</td><td>{dash(bn(m.monthly.at(-1)?.end||0))}</td></tr></tbody></table><p className="tableFoot">The volume-weighted average market price for the year equals the fixed price. K is the year's own average, not a margin above it.</p></div>
  <div className="method"><b>Formula</b><code>units × max(market price × scenario − K, 0)</code><span>Starting pool = NPV of the unshocked 2025 monthly payout stream at the selected fund return × (1 + loading).</span></div>
 </section>;
}

const css=`
.pgx{--pool:var(--data-pool,#004D73);--guarantor:var(--data-guarantor,#BE7C1C);--chrome:#1A3C5A;--ink:var(--article-ink,#1A1A18);--ink2:var(--article-ink-2,#5A5A54);--ink3:var(--article-ink-3,#7A776E);--rule:var(--article-rule,#D8D4CC);--grid:var(--article-grid,#E5E1D8);--hourly:#8FC7E8;margin:52px 0 60px;border-top:4px solid var(--chrome);padding-top:18px;font-family:Arial;color:var(--ink)}
.top{max-width:760px}.top>span,.panel>span,.table>div>span,.callout span{font-size:9px;font-weight:900;letter-spacing:.14em;color:var(--chrome)}.top h2{font:700 35px/1.02 var(--reader-font,Georgia,serif);margin:6px 0 9px;color:var(--ink)}.top p{font:13.5px/1.5 Arial;color:var(--ink2);margin:0}
.controls{margin:22px 0}.controlGroup{display:grid;grid-template-columns:repeat(3,1fr);gap:18px}.stressGroup{margin-top:16px;padding-top:16px;border-top:1px solid var(--rule)}.controls label{font-size:9px;font-weight:800;letter-spacing:.06em;text-transform:uppercase;color:var(--ink3)}.rawUnit{text-transform:none!important;letter-spacing:normal}.controls input,.controls select{box-sizing:border-box;color:var(--ink);font:600 12px Arial;accent-color:var(--chrome)}.number,.typed,.controls select{margin-top:7px;width:100%;border:1px solid var(--rule);background:var(--reader-surface,#FBF8F3)}.number{padding:10px}.typed{display:flex;align-items:center;min-width:118px}.typed input{width:100%;min-width:0;border:0;background:transparent;padding:10px;outline:0;font-variant-numeric:tabular-nums}.typed span{padding:0 10px;color:var(--ink2);font-size:11px}.dual{margin-top:7px;display:grid;grid-template-columns:minmax(118px,auto) 1fr;gap:12px;align-items:center}.dual .typed{margin:0}.controls select{padding:10px 32px 10px 10px;appearance:none;background-image:linear-gradient(45deg,transparent 50%,var(--chrome) 50%),linear-gradient(135deg,var(--chrome) 50%,transparent 50%);background-position:calc(100% - 14px) 50%,calc(100% - 9px) 50%;background-size:5px 5px;background-repeat:no-repeat}input[type=range]{appearance:none;height:18px;background:transparent}input[type=range]::-webkit-slider-runnable-track{height:3px;background:var(--rule)}input[type=range]::-webkit-slider-thumb{appearance:none;width:14px;height:14px;border-radius:50%;background:var(--chrome);border:2px solid var(--reader-bg,#F7F1E8);margin-top:-5px}input[type=range]::-moz-range-track{height:3px;background:var(--rule)}input[type=range]::-moz-range-thumb{width:12px;height:12px;border-radius:50%;background:var(--chrome);border:2px solid var(--reader-bg,#F7F1E8)}input:focus,select:focus{outline:2px solid var(--chrome);outline-offset:2px}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--rule);margin-top:20px}.kpis div{padding:14px 14px 14px 16px;border-right:1px solid var(--rule)}.kpis div:last-child{border-right:0}.kpis span{display:block;font-size:11px;font-weight:600;letter-spacing:.07em;text-transform:uppercase;color:var(--ink3)}.kpis b{display:block;font:700 24px var(--reader-font,Georgia,serif);margin:5px 0;color:var(--ink);font-variant-numeric:tabular-nums}.kpis small{font:400 12.5px/1.3 Arial;color:var(--ink2)}
.callout{padding:16px 0;border-top:1px solid var(--rule)}.callout b{display:block;font:700 19px/1.3 var(--reader-font,Georgia,serif);margin-top:5px;color:var(--ink)}
.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;align-items:stretch}.panel,.table{padding:15px 0;background:transparent;border-top:1px solid var(--rule)}.panel h3,.table h3{font:700 20px/1.1 var(--reader-font,Georgia,serif);margin:5px 0 12px;color:var(--ink)}.poolPanel{margin-top:0}
.chart{position:relative;break-inside:avoid}.chart svg{display:block;width:100%;height:235px;overflow:visible}.poolPanel .chart svg{height:245px}.chart svg text{font:8px Arial;fill:var(--ink3)}.chart svg .markerLabel{fill:var(--ink2)}.gridline{stroke:var(--grid);stroke-width:.7}.gridline.zero,.axisline{stroke:var(--rule);stroke-width:1}.unit{font:800 8px Arial;color:var(--ink3);margin:0 0 2px}.legend{display:flex;flex-wrap:wrap;gap:18px;align-items:center;margin-top:10px;color:var(--ink2);font:9px/1 Arial}.legendItem{display:inline-flex;align-items:center;gap:7px;white-space:nowrap}.legendItem svg{display:block;flex:0 0 10px;height:10px!important;width:10px!important}.chartFooter{border-top:1px solid var(--rule);margin-top:10px;padding-top:7px;font:8px/1.45 Arial;color:var(--ink2)}.chartFooter span{display:block}
.shapeNote{padding:13px 0;border-top:1px solid var(--rule);font:10px/1.5 Arial;color:var(--ink2)}.shapeNote b{color:var(--ink)}.shapeChart{padding:10px 0 14px;break-inside:avoid}.shapeRows{display:grid;gap:10px;margin-top:6px}.shapeRow{display:grid;grid-template-columns:120px minmax(0,1fr) 120px;gap:12px;align-items:center}.shapeName{text-align:right;font:10px Arial;color:var(--ink);white-space:nowrap}.shapeBar{display:block;width:100%;height:14px}.shapeValue{font:10px Arial;color:var(--ink);font-variant-numeric:tabular-nums;white-space:nowrap}.shapeValue em{font-style:normal;color:var(--ink2);margin-left:4px}
.table{overflow:auto}.scenarioLine,.tableFoot{font:9px Arial;color:var(--ink2);margin:0 0 8px}.tableFoot{margin:8px 0 0}.table table{width:100%;border-collapse:collapse;font:10px/1.25 Arial;white-space:nowrap;font-variant-numeric:tabular-nums;border-top:1px solid var(--rule)}.table th,.table td{text-align:right;padding:8px;border-bottom:.5px solid var(--rule);color:var(--ink)}.table th:first-child,.table td:first-child{text-align:left}.table th{font-size:8px;text-transform:uppercase;color:var(--ink3)}.table tbody tr:last-child td{border-bottom:1px solid var(--rule)}.table .total td{font-weight:800;border-top:1px solid var(--rule)}.opening td{color:var(--ink2)}
.method{padding:13px 0;border-top:3px solid var(--chrome);font:10px/1.5 Arial;color:var(--ink2)}.method b,.method code,.method span{display:block}.method b{color:var(--chrome);font-size:9px;letter-spacing:.12em;text-transform:uppercase}.method code{margin:5px 0;font-size:11px;color:var(--ink)}
.pgx a{color:var(--ink);text-underline-offset:3px}
@media(max-width:900px){.controlGroup{grid-template-columns:1fr}.grid{grid-template-columns:1fr}.kpis{grid-template-columns:1fr 1fr}.shapeRow{grid-template-columns:94px minmax(0,1fr) 100px}}
@media print{.pgx{--pool:#004D73;--guarantor:#BE7C1C;--hourly:#8FC7E8;--ink:#1A1A18;--ink2:#5A5A54;--ink3:#7A776E;--rule:#D8D4CC;--grid:#E5E1D8;-webkit-print-color-adjust:exact;print-color-adjust:exact}.controls{display:none}.chart,.shapeChart,.panel,.table,.kpis,.callout,.method{break-inside:avoid}.chart svg{display:block!important;width:100%!important;height:235px!important}.poolPanel .chart svg{height:245px!important}.grid{display:block}.grid .panel{margin-bottom:12px}.legendItem svg,.shapeBar{print-color-adjust:exact;-webkit-print-color-adjust:exact}}
`;
