"use client";

import {useEffect,useMemo,useState} from "react";

type Row={district:string;province:string;year:number;infection:number;privateBeds:number;publicBeds:number;population:number};
type GeoFeature={properties:Record<string,any>;geometry:{type:string;coordinates:any}};
type GeoJSON={type:string;features:GeoFeature[]};

const GEO_URL="https://raw.githubusercontent.com/PakData/GISData/master/PAK-GeoJSON/PAK_adm3.json";
const DATA:Row[]=[
{district:"Lahore",province:"Punjab",year:2022,infection:10.1,privateBeds:7600,publicBeds:5900,population:12600000},{district:"Lahore",province:"Punjab",year:2023,infection:11.3,privateBeds:8010,publicBeds:6000,population:12800000},{district:"Lahore",province:"Punjab",year:2024,infection:12.4,privateBeds:8450,publicBeds:6180,population:13004135},
{district:"Faisalabad",province:"Punjab",year:2022,infection:8.8,privateBeds:3400,publicBeds:4200,population:8600000},{district:"Faisalabad",province:"Punjab",year:2023,infection:9.6,privateBeds:3650,publicBeds:4310,population:8860000},{district:"Faisalabad",province:"Punjab",year:2024,infection:10.1,privateBeds:3910,publicBeds:4450,population:9075319},
{district:"Rawalpindi",province:"Punjab",year:2022,infection:8.1,privateBeds:4180,publicBeds:3320,population:5700000},{district:"Rawalpindi",province:"Punjab",year:2023,infection:8.8,privateBeds:4520,publicBeds:3440,population:5920000},{district:"Rawalpindi",province:"Punjab",year:2024,infection:9.4,privateBeds:4770,publicBeds:3560,population:6119395},
{district:"Multan",province:"Punjab",year:2022,infection:12.9,privateBeds:2810,publicBeds:2900,population:5000000},{district:"Multan",province:"Punjab",year:2023,infection:13.8,privateBeds:3000,publicBeds:3010,population:5200000},{district:"Multan",province:"Punjab",year:2024,infection:14.6,privateBeds:3180,publicBeds:3150,population:5362017},
{district:"Peshawar",province:"Khyber Pakhtunkhwa",year:2022,infection:14.1,privateBeds:2350,publicBeds:3180,population:4400000},{district:"Peshawar",province:"Khyber Pakhtunkhwa",year:2023,infection:15.5,privateBeds:2540,publicBeds:3300,population:4580000},{district:"Peshawar",province:"Khyber Pakhtunkhwa",year:2024,infection:16.9,privateBeds:2750,publicBeds:3430,population:4758762},
{district:"Quetta",province:"Balochistan",year:2022,infection:11.9,privateBeds:1410,publicBeds:2450,population:2320000},{district:"Quetta",province:"Balochistan",year:2023,infection:12.5,privateBeds:1540,publicBeds:2520,population:2460000},{district:"Quetta",province:"Balochistan",year:2024,infection:13.2,privateBeds:1680,publicBeds:2600,population:2595368},
{district:"Sialkot",province:"Punjab",year:2022,infection:6.7,privateBeds:1740,publicBeds:1880,population:4210000},{district:"Sialkot",province:"Punjab",year:2023,infection:7.3,privateBeds:1860,publicBeds:1940,population:4370000},{district:"Sialkot",province:"Punjab",year:2024,infection:7.9,privateBeds:1980,publicBeds:2010,population:4499115},
{district:"Gujranwala",province:"Punjab",year:2022,infection:7.8,privateBeds:1880,publicBeds:2110,population:5100000},{district:"Gujranwala",province:"Punjab",year:2023,infection:8.4,privateBeds:2050,publicBeds:2170,population:5270000},{district:"Gujranwala",province:"Punjab",year:2024,infection:9.0,privateBeds:2240,publicBeds:2230,population:5450000}
];

const norm=(x:any)=>String(x??"").toLowerCase().replace(/district|division|city|province|tehsil/g,"").replace(/[^a-z0-9]/g,"");
function flatten(c:any,o:number[][]=[]):number[][]{if(!Array.isArray(c))return o;if(typeof c[0]==="number"&&typeof c[1]==="number")o.push(c);else c.forEach((x:any)=>flatten(x,o));return o}
function path(f:GeoFeature,b:any,w=760,h=620){const a=f.geometry.type==="Polygon"?f.geometry.coordinates:f.geometry.coordinates.flat();const sx=(x:number)=>18+(x-b.minX)/(b.maxX-b.minX||1)*(w-36),sy=(y:number)=>18+(b.maxY-y)/(b.maxY-b.minY||1)*(h-36);return a.map((r:any)=>r.map((p:number[],i:number)=>`${i?"L":"M"}${sx(p[0]).toFixed(1)},${sy(p[1]).toFixed(1)}`).join(" ")+" Z").join(" ")}
function fmt(n:number){return n>=1_000_000?(n/1_000_000).toFixed(1)+"m":n.toLocaleString()}

export default function VisualBenchmarkStory(){
 const[year,setYear]=useState(2024),[metric,setMetric]=useState<"infection"|"privateBeds"|"publicBeds">("infection"),[province,setProvince]=useState("All"),[selected,setSelected]=useState<string[]>([]),[hover,setHover]=useState<string>("");
 const[geo,setGeo]=useState<GeoJSON|null>(null);
 useEffect(()=>{fetch(GEO_URL).then(r=>r.json()).then(setGeo).catch(()=>{})},[]);
 const rows=useMemo(()=>DATA.filter(r=>r.year===year&&(province==="All"||r.province===province)&&(!selected.length||selected.includes(r.district))),[year,province,selected]);
 const allYear=useMemo(()=>DATA.filter(r=>province==="All"||r.province===province),[province]);
 const vals=rows.map(r=>r[metric]);const min=Math.min(...(vals.length?vals:[0])),max=Math.max(...(vals.length?vals:[1]));
 const idx=useMemo(()=>new Map(DATA.filter(r=>r.year===year).map(r=>[norm(r.district),r])),[year]);
 const b=useMemo(()=>{if(!geo)return null;const z=geo.features.flatMap(f=>flatten(f.geometry.coordinates));return{minX:Math.min(...z.map(x=>x[0])),maxX:Math.max(...z.map(x=>x[0])),minY:Math.min(...z.map(x=>x[1])),maxY:Math.max(...z.map(x=>x[1]))}},[geo]);
 const ranked=[...rows].sort((a,b)=>b[metric]-a[metric]);
 const xMax=Math.max(...rows.map(r=>r.privateBeds),1),yMax=Math.max(...rows.map(r=>r.infection),1);
 const years=[2022,2023,2024];
 function toggle(d:string){setSelected(s=>s.includes(d)?s.filter(x=>x!==d):[...s,d])}
 function fill(v:number|undefined,on:boolean){if(v==null)return"rgba(0,77,115,.05)";const t=(v-min)/(max-min||1);return on?"rgba(0,77,115,.95)":`rgba(0,77,115,${.12+t*.75})`}
 return <section className="vb"><style>{css}</style>
  <div className="controls"><label>Year<select value={year} onChange={e=>setYear(+e.target.value)}>{years.map(y=><option key={y}>{y}</option>)}</select></label><label>Map metric<select value={metric} onChange={e=>setMetric(e.target.value as any)}><option value="infection">Infection ratio</option><option value="privateBeds">Private beds</option><option value="publicBeds">Public beds</option></select></label><label>Province<select value={province} onChange={e=>{setProvince(e.target.value);setSelected([])}}><option>All</option><option>Punjab</option><option>Khyber Pakhtunkhwa</option><option>Balochistan</option></select></label><button onClick={()=>setSelected([])}>Clear selection</button></div>
  <div className="grid">
   <article className="card mapCard"><div className="head"><div><span>MAP</span><h3>{metric==="infection"?"Infection burden":metric==="privateBeds"?"Private hospital capacity":"Public hospital capacity"}</h3></div><small>Click districts to cross-filter every visual</small></div>{geo&&b?<svg viewBox="0 0 760 620" className="map">{geo.features.map((f,i)=>{const name=String(f.properties.NAME_3||"");const r=idx.get(norm(name));const active=selected.includes(name);const visible=!selected.length||active;return <path key={f.properties.GID_3||i} d={path(f,b)} fill={fill(r?.[metric],active)} opacity={province!=="All"&&r?.province!==province?.22:visible?1:.18} stroke="rgba(32,36,38,.35)" strokeWidth=".6" onMouseEnter={()=>setHover(name)} onMouseLeave={()=>setHover("")} onClick={()=>r&&toggle(r.district)}/>})}</svg>:<div className="loading">Loading district boundaries…</div>}{hover&&<div className="hover">{hover}{idx.get(norm(hover))&&<><b>{idx.get(norm(hover))?.infection}% infection</b><b>{fmt(idx.get(norm(hover))?.privateBeds||0)} private beds</b></>}</div>}</article>
   <article className="card"><div className="head"><div><span>RANK</span><h3>District comparison</h3></div><small>Same filter state as map</small></div><div className="bars">{ranked.map(r=><div className="bar" key={r.district} onClick={()=>toggle(r.district)}><em>{r.district}</em><i><b style={{width:`${(r[metric]/Math.max(...ranked.map(x=>x[metric]),1))*100}%`}}/></i><strong>{metric==="infection"?r[metric].toFixed(1)+"%":fmt(r[metric])}</strong></div>)}</div></article>
   <article className="card"><div className="head"><div><span>RELATIONSHIP</span><h3>Infection vs private capacity</h3></div><small>Hover or select outliers</small></div><svg viewBox="0 0 640 360" className="scatter">{rows.map(r=>{const x=45+r.privateBeds/xMax*555,y=310-r.infection/yMax*250;return <g key={r.district} onClick={()=>toggle(r.district)}><circle cx={x} cy={y} r={selected.includes(r.district)?10:7}/><text x={x+8} y={y-6}>{r.district}</text></g>})}<line x1="45" y1="310" x2="610" y2="310"/><line x1="45" y1="40" x2="45" y2="310"/></svg></article>
   <article className="card"><div className="head"><div><span>TREND</span><h3>Infection ratio over time</h3></div><small>Selected districts only, or all</small></div><div className="trends">{Array.from(new Set(allYear.map(r=>r.district))).filter(d=>!selected.length||selected.includes(d)).map(d=>{const rr=DATA.filter(r=>r.district===d&&(province==="All"||r.province===province));return <div className="trend" key={d}><b>{d}</b><div>{rr.map((r,i)=><span key={r.year}><small>{r.year}</small><strong>{r.infection}%</strong>{i<rr.length-1&&<i/>}</span>)}</div></div>})}</div></article>
  </div>
  <div className="qa"><div><span>DATA QUALITY</span><b>24 rows · 8 districts · 3 years · no missing values</b></div><div><span>INTERACTION STATE</span><b>{selected.length?selected.join(", "):"All districts"}</b></div><div><span>PROVENANCE</span><b>Synthetic benchmark dataset for product testing</b></div></div>
 </section>
}

const css=`
.vb{font-family:Inter,Arial,sans-serif;color:#202426}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:18px 0 22px}.controls label{font-size:11px;font-weight:800;letter-spacing:.06em}.controls select,.controls button{display:block;margin-top:5px;border:1px solid #cfc8bd;background:#fbf8f3;padding:9px 10px;color:#202426}.controls button{margin-top:19px;cursor:pointer}.grid{display:grid;grid-template-columns:1.25fr .75fr;gap:18px}.card{border:1px solid #d8d4cd;background:#fbf8f3;padding:18px;position:relative;min-height:390px}.mapCard{grid-row:span 2}.head{display:flex;justify-content:space-between;gap:20px;margin-bottom:14px}.head span,.qa span{font-size:10px;font-weight:900;letter-spacing:.14em;color:#004d73}.head h3{font:700 25px Georgia,serif;margin:4px 0}.head small{color:#707678}.map{width:100%;height:600px;cursor:pointer}.hover{position:absolute;right:18px;bottom:18px;background:#202426;color:#fff;padding:12px;display:grid;gap:5px;font-size:12px}.bars{display:grid;gap:8px}.bar{display:grid;grid-template-columns:110px 1fr 70px;align-items:center;gap:8px;cursor:pointer}.bar em{font-style:normal;font-size:12px}.bar i{height:10px;background:#e6e0d6}.bar i b{display:block;height:100%;background:#004d73}.bar strong{text-align:right;font-size:12px}.scatter{width:100%;height:320px}.scatter circle{fill:#004d73;cursor:pointer}.scatter text{font-size:11px}.scatter line{stroke:#a9a39b;stroke-width:1}.trends{display:grid;gap:10px;max-height:320px;overflow:auto}.trend{border-bottom:1px solid #e2ddd4;padding-bottom:8px}.trend>b{font-size:12px}.trend>div{display:flex;gap:10px;margin-top:6px}.trend span{display:grid;position:relative;padding-right:15px}.trend span i{position:absolute;right:0;top:17px;width:12px;border-top:1px solid #8d9395}.trend small{font-size:10px;color:#777}.trend strong{font-size:12px}.qa{display:grid;grid-template-columns:repeat(3,1fr);gap:1px;background:#d8d4cd;margin-top:18px}.qa>div{background:#f7f1e8;padding:14px;display:grid;gap:5px}.qa b{font-size:12px}.loading{padding:80px;text-align:center;color:#777}@media(max-width:900px){.grid{grid-template-columns:1fr}.mapCard{grid-row:auto}.qa{grid-template-columns:1fr}.map{height:450px}}
`;
